# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecafegraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ControlPanel(object):
    def setupUi(self, ControlPanel):
        ControlPanel.setObjectName("ControlPanel")
        ControlPanel.resize(554, 301)
        ControlPanel.setStyleSheet("background: #2B3440;")
        self.centralwidget = QtWidgets.QWidget(ControlPanel)
        self.centralwidget.setObjectName("centralwidget")
        self.showframe = QtWidgets.QFrame(self.centralwidget)
        self.showframe.setGeometry(QtCore.QRect(20, 20, 521, 261))
        self.showframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.showframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.showframe.setObjectName("showframe")
        self.label_4 = QtWidgets.QLabel(self.showframe)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 511, 71))
        self.label_4.setStyleSheet("color: #FF971A;\n"
"font: 48pt \"MS UI Gothic\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.showframe)
        self.label_5.setGeometry(QtCore.QRect(180, 90, 151, 71))
        self.label_5.setStyleSheet("color: #FF971A;\n"
"font:18pt \"MS UI Gothic\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.showframe)
        self.label_6.setGeometry(QtCore.QRect(170, 140, 181, 41))
        self.label_6.setStyleSheet("color: #FF971A;\n"
"font:10pt \"MS UI Gothic\";")
        self.label_6.setObjectName("label_6")
        self.btop = QtWidgets.QPushButton(self.showframe)
        self.btop.setGeometry(QtCore.QRect(10, 190, 151, 41))
        self.btop.setStyleSheet("QPushButton\n"
"{\n"
"background:#2B3440;\n"
"color:#FF971A;\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background:#FFFFFF;\n"
"color:#FF971A;\n"
"}")
        self.btop.setObjectName("btop")
        self.bleast = QtWidgets.QPushButton(self.showframe)
        self.bleast.setGeometry(QtCore.QRect(180, 190, 151, 41))
        self.bleast.setStyleSheet("QPushButton\n"
"{\n"
"background:#2B3440;\n"
"color:#FF971A;\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background:#FFFFFF;\n"
"color:#FF971A;\n"
"}")
        self.bleast.setObjectName("bleast")
        self.bactive = QtWidgets.QPushButton(self.showframe)
        self.bactive.setGeometry(QtCore.QRect(350, 190, 151, 41))
        self.bactive.setStyleSheet("QPushButton\n"
"{\n"
"background:#2B3440;\n"
"color:#FF971A;\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background:#FFFFFF;\n"
"color:#FF971A;\n"
"}")
        self.bactive.setObjectName("bactive")
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.btop.raise_()
        self.bleast.raise_()
        self.bactive.raise_()
        ControlPanel.setCentralWidget(self.centralwidget)

        self.retranslateUi(ControlPanel)
        QtCore.QMetaObject.connectSlotsByName(ControlPanel)

    def retranslateUi(self, ControlPanel):
        _translate = QtCore.QCoreApplication.translate
        ControlPanel.setWindowTitle(_translate("ControlPanel", "E-Cafe Control Panel"))
        self.label_4.setWhatsThis(_translate("ControlPanel", "<html><head/><body><p><br/></p></body></html>"))
        self.label_4.setText(_translate("ControlPanel", "TUPC E-Cafeteria"))
        self.label_5.setWhatsThis(_translate("ControlPanel", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("ControlPanel", "Control Panel"))
        self.label_6.setWhatsThis(_translate("ControlPanel", "<html><head/><body><p><br/></p></body></html>"))
        self.label_6.setText(_translate("ControlPanel", "Press buttons to show output"))
        self.btop.setText(_translate("ControlPanel", "TOP SELLING"))
        self.bleast.setText(_translate("ControlPanel", "LEAST SELLING"))
        self.bactive.setText(_translate("ControlPanel", "ACTIVE TIME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ControlPanel = QtWidgets.QMainWindow()
    ui = Ui_ControlPanel()
    ui.setupUi(ControlPanel)
    ControlPanel.show()
    sys.exit(app.exec_())
